import 'package:fluttereticket/models/showTickets.dart';
import 'package:fluttereticket/models/partyTickets.dart';
import 'package:fluttereticket/models/visitTickets.dart';
import 'package:fluttereticket/models/travelTickets.dart';

List<dynamic> tickets = [
  ShowTicket(
      logo: "ic.jpeg",
      ticketId: "29865743",
      purchaseDate: "12.11.2019",
      title: "Internatinal Cineplex",
      hallAddress: "Am Olympiapark 2, 80809 Müchen",
      showTitle: "Lord of the Rings",
      theater: "01",
      row: "07",
      column: "12",
      showDate: "12.04.2019",
      showTime: "19:00",
      price: "19",
      valid: true,
      used: false
  ),
  PartyTicket(
      logo: "ny.jpeg",
      ticketId: "29865743",
      purchaseDate: "12.11.2019",
      title: "New Year Party",
      address: "Zeil 9, 9058 Frankfurt",
      artist: "The Amazing Spiderman",
      startTime: "07:00",
      endTime: "12:00",
      date: "12.04.2019",
      price: "13",
      valid: true,
      used: false
  ),
  ShowTicket(
      logo: "ic.jpeg",
      ticketId: "29865743",
      purchaseDate: "12.11.2019",
      title: "Internatinal Cineplex",
      hallAddress: "Am Olympiapark 2, 80809 Müchen",
      showTitle: "Lord of the Rings",
      theater: "01",
      row: "07",
      column: "12",
      showDate: "12.04.2019",
      showTime: "19:00",
      price: "15",
      valid: true,
      used: false
  ),
  TravelTicket(
      logo: "rmv.jpeg",
      ticketId: "29865743",
      title: "Day Ticket",
      transportation: "RMV Bus",
      from: "5000",
      to: "5000",
      through: "0000",
      purchaseDate: "12.11.2019",
      price: "12",
      valid: false,
      used: true
  ),
  VisitTicket(
      logo: "bmw.jpeg",
      ticketId: "29865743",
      purchaseDate: "12.11.2019",
      title: "BMW Museum",
      address: "Am Olympiapark 2, 80809 Müchen",
      openTime: "09:00",
      closeTime: "19:00",
      lastEntry: "18:00",
      price: "5",
      validity: "Ticket is for one time use after purchase",
      valid: false,
      used: true
  ),
  PartyTicket(
      logo: "sn.jpeg",
      ticketId: "29865743",
      purchaseDate: "12.11.2019",
      title: "New Year Party",
      address: "Zeil 9, 9058 Frankfurt",
      artist: "The Amazing Spiderman",
      startTime: "07:00",
      endTime: "12:00",
      date: "12.04.2019",
      price: "13",
      valid: false,
      used: false
  ),
  VisitTicket(
      logo: "ic.jpeg",
      ticketId: "29865743",
      purchaseDate: "12.11.2019",
      title: "Frankfurt Tower",
      address: "Am Olympiapark 2, 80809 Müchen",
      openTime: "09:00",
      closeTime: "19:00",
      lastEntry: "18:00",
      price: "5",
      validity: "Ticket is for one time use after purchase",
      valid: false,
      used: false
  ),
  ShowTicket(
      logo: "ic.jpeg",
      ticketId: "29865743",
      purchaseDate: "12.11.2019",
      title: "Internatinal Cineplex",
      hallAddress: "Am Olympiapark 2, 80809 Müchen",
      showTitle: "Lord of the Rings",
      theater: "01",
      row: "07",
      column: "12",
      showDate: "12.04.2019",
      showTime: "19:00",
      price: "19",
      valid: true,
      used: false
  ),
];
